const fs = require('fs');
const path = require('path');
const { scanTemplate } = require('./templateScan');

const TEMPLATE_PATH = path.join(__dirname, '..', '..', 'wall_template_default.jpg');
const OUTPUT_PATH = path.join(__dirname, '..', '..', 'public', 'zone-positions.css');

function cssFor(scan) {
  const { canvasWidth, canvasHeight, zones } = scan;
  const { left, middle, rightTop, rightMiddle, rightBottom } = zones;
  const box = (name, z) =>
    `  --${name}-x: ${z.x}px;\n  --${name}-y: ${z.y}px;\n  --${name}-w: ${z.w}px;\n  --${name}-h: ${z.h}px;\n`;

  return (
    '/* AUTO-GENERATED by server/services/zonePositions.js - do not hand-edit.\n' +
    '   Regenerated from wall_template_default.jpg on every server start, so\n' +
    '   replacing that file is all that is needed for minor box drift. */\n' +
    ':root {\n' +
    `  --canvas-width: ${canvasWidth}px;\n` +
    `  --canvas-height: ${canvasHeight}px;\n\n` +
    box('middle', middle) + '\n' +
    box('left', left) + '\n' +
    box('right-top', rightTop) + '\n' +
    box('right-middle', rightMiddle) + '\n' +
    box('right-bottom', rightBottom) +
    '}\n'
  );
}

// Rescans wall_template_default.jpg and regenerates public/zone-positions.css.
// Never throws - a scan failure (missing file, or a real structural layout
// change the classifier can't map) is logged and the previous generated
// CSS is left in place untouched, so the wall keeps running on the last
// known-good layout instead of going down over a template mismatch.
function regenerateZoneCss() {
  try {
    const scan = scanTemplate(TEMPLATE_PATH);
    fs.writeFileSync(OUTPUT_PATH, cssFor(scan));
    console.log(
      `[zone-scan] OK - middle ${scan.zones.middle.w}x${scan.zones.middle.h}, ` +
        `left ${scan.zones.left.w}x${scan.zones.left.h}, ` +
        `right boxes ${scan.zones.rightTop.w}x${scan.zones.rightTop.h}`
    );
    return { ok: true, scan };
  } catch (err) {
    console.error(`[zone-scan] FAILED: ${err.message}`);
    if (fs.existsSync(OUTPUT_PATH)) {
      console.error('[zone-scan] Keeping previous public/zone-positions.css (last known good) - wall keeps running.');
    } else {
      console.error(
        '[zone-scan] No previous public/zone-positions.css exists - falling back to the hardcoded defaults in style.css.'
      );
    }
    return { ok: false, error: err.message };
  }
}

module.exports = { regenerateZoneCss, TEMPLATE_PATH, OUTPUT_PATH };
