const fs = require('fs');
const path = require('path');
const { scanTemplate } = require('./templateScan');
const { setZoneScanStatus } = require('../state');

const TEMPLATE_PATH = path.join(__dirname, '..', '..', 'wall box positions.jpg');
const OUTPUT_PATH = path.join(__dirname, '..', '..', 'public', 'zone-positions.css');

function cssFor(scan) {
  const { canvasWidth, canvasHeight, zones } = scan;
  const { left, middle, right, prayers } = zones;
  const box = (name, z) =>
    `  --${name}-x: ${z.x}px;\n  --${name}-y: ${z.y}px;\n  --${name}-w: ${z.w}px;\n  --${name}-h: ${z.h}px;\n`;

  return (
    '/* AUTO-GENERATED by server/services/zonePositions.js - do not hand-edit,\n' +
    '   it will be overwritten on the next scan. Regenerated from\n' +
    '   "wall box positions.jpg" by the "Scan Template Now" button on\n' +
    '   /control (or `npm run scan-template`) - NOT automatically on server\n' +
    '   start. Re-run one of those after replacing that file. */\n' +
    ':root {\n' +
    `  --canvas-width: ${canvasWidth}px;\n` +
    `  --canvas-height: ${canvasHeight}px;\n\n` +
    box('middle', middle) + '\n' +
    box('left', left) + '\n' +
    box('right', right) + '\n' +
    box('prayers', prayers) +
    '}\n'
  );
}

// Rescans "wall box positions.jpg" and regenerates public/zone-positions.css.
// Never throws - a scan failure (missing file, or a real structural layout
// change the classifier can't map) is logged and the previous generated
// CSS is left in place untouched, so the wall keeps running on the last
// known-good layout instead of going down over a template mismatch.
function regenerateZoneCss() {
  try {
    const scan = scanTemplate(TEMPLATE_PATH);
    fs.writeFileSync(OUTPUT_PATH, cssFor(scan));
    console.log(
      `[zone-scan] OK - middle ${scan.zones.middle.w}x${scan.zones.middle.h}, ` +
        `left ${scan.zones.left.w}x${scan.zones.left.h}, ` +
        `right ${scan.zones.right.w}x${scan.zones.right.h}, ` +
        `prayers ${scan.zones.prayers.w}x${scan.zones.prayers.h}`
    );
    setZoneScanStatus({
      lastScanAt: new Date().toISOString(),
      lastScanOk: true,
      lastScanError: null,
      zones: {
        middle: { w: scan.zones.middle.w, h: scan.zones.middle.h },
        left: { w: scan.zones.left.w, h: scan.zones.left.h },
        right: { w: scan.zones.right.w, h: scan.zones.right.h },
        prayers: { w: scan.zones.prayers.w, h: scan.zones.prayers.h },
      },
    });
    return { ok: true, scan };
  } catch (err) {
    console.error(`[zone-scan] FAILED: ${err.message}`);
    if (fs.existsSync(OUTPUT_PATH)) {
      console.error('[zone-scan] Keeping previous public/zone-positions.css (last known good) - wall keeps running.');
    } else {
      console.error(
        '[zone-scan] No previous public/zone-positions.css exists - falling back to the hardcoded defaults in style.css.'
      );
    }
    setZoneScanStatus({ lastScanAt: new Date().toISOString(), lastScanOk: false, lastScanError: err.message });
    return { ok: false, error: err.message };
  }
}

module.exports = { regenerateZoneCss, TEMPLATE_PATH, OUTPUT_PATH };
